name: Terraform Preprod

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  terraform:

    name: Deploy Preprod
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: environment/preprod

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: "daa47584-8ad5-403b-9073-015c77c0f57c"
          tenant-id: "1ce567c7-283d-4272-b4bd-8292e9e4cd20"
          subscription-id: "617408c3-ce8d-4f34-a887-db4cd7d25b4e"

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format
        run: terraform fmt -check -recursive

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -var-file="terraform.tfvars"

      - name: Terraform Apply
        run: terraform apply -auto-approve -var-file="terraform.tfvars"

   